/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class Map */

#ifndef _Included_Map
#define _Included_Map
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Map
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Map_init
  (JNIEnv *, jclass);

/*
 * Class:     Map
 * Method:    generate
 * Signature: (I[I[I)V
 */
JNIEXPORT void JNICALL Java_Map_generate
  (JNIEnv *, jclass, jint, jintArray, jintArray);

/*
 * Class:     Map
 * Method:    solve
 * Signature: ([IZZ)I
 */
JNIEXPORT jint JNICALL Java_Map_solve
  (JNIEnv *, jclass, jintArray, jboolean, jboolean);

#ifdef __cplusplus
}
#endif
#endif
